### ISSUE TITLE
Regression in v0.15+: generate_direct_lake_semantic_model() no longer supports overwrite, preventing in-place semantic model updates

### ISSUE THREAD

**Issue by Vera-OT** [microsoft/semantic-link-labs#1270]
## Describe the bug

Starting with Semantic Link Labs v0.15.x, the `overwrite` parameter appears to have been removed from `directlake.generate_direct_lake_semantic_model()`.

In v0.14.3 and earlier, we successfully used:

```
directlake.generate_direct_lake_semantic_model(
    dataset=model_name,
    lakehouse_tables=table_names,
    lakehouse=lakehouse_name,
    workspace=workspace_name,
    overwrite=True
)
```

to regenerate an existing Direct Lake semantic model while preserving the semantic model identity and existing report bindings.

After upgrading to v0.15.x, the `overwrite` parameter is no longer available, which prevents us from updating an existing semantic model through the same workflow. We have to create a new semantic model and rebind reports.

## To Reproduce

1. Install or use Semantic Link Labs v0.15.x or later.
2. Attempt to execute:

```
directlake.generate_direct_lake_semantic_model(
    dataset=model_name,
    tables=table_names,
    source=lakehouse_name,
    source_type="Lakehouse",
    source_workspace=workspace_name, 
    overwrite=True
)
```

3. Observe that the function no longer accepts the `overwrite` argument.
```
TypeError
got an unexpected keyword argument 'overwrite'
```

## Expected behavior

Keep the 'overwrite' argument available.

## Screenshots

v0.14.3
<img width="1383" height="908" alt="Image" src="https://github.com/user-attachments/assets/57f75e5b-5c67-4269-b12a-85e18abb99ff" />

Latest

<img width="1647" height="979" alt="Image" src="https://github.com/user-attachments/assets/22c1658f-42f4-4ee0-a0a9-51136982530e" />

## Desktop (please complete the following information)

* OS: Windows 11, Microsoft Fabric Notebook Runtime
* Browser: Edge/Chrome
* Semantic Link Labs version:

  * Working: v0.14.3
  * Issue observed: v0.15.x and later

## Additional context

If this functionality (i.e., overwrite) has intentionally been removed, could you please advise on the recommended approach for performing a full semantic model replacement/update while preserving the existing semantic model and report bindings? Thank you!

**Comment by m-kovalsky** [comment]
Fixed in [0.16.0](https://github.com/microsoft/semantic-link-labs/releases/tag/0.16.0).
