### ISSUE TITLE
AttributeError when using set_synonym() function

### ISSUE THREAD

**Issue by aakashb14** [microsoft/semantic-link-labs#766]
I'm trying to set synonyms for a table in the semantic model using set_synonym() function within TOM but running into the the error below.

**Code**

%pip install semantic-link-labs 0.11.1
import sempy.fabric as fabric
import sempy_labs as labs
from sempy_labs.tom import connect_semantic_model
from sempy_labs.tom._model import TOMWrapper

with connect_semantic_model(dataset=dataset, workspace=workspace, readonly=False) as tom:
    tom.set_synonym(culture = 'en-US', object = tom.model.Tables['TableName'], synonym_name = 'some synonym')

Alternatively, I also tried the code below but get the same error:

with connect_semantic_model(dataset=dataset, workspace=workspace, readonly=False) as tom:
    tom.set_synonym(culture = 'en-US', object ='TableName', synonym_name = 'some synonym')

**Error message**

AttributeError                            Traceback (most recent call last)
Cell In[58], line 2
      1 with connect_semantic_model(dataset=dataset, workspace=workspace, readonly=False) as tom:
----> 2     tom.set_synonym(culture = 'en-US', object = 'Terms', synonym_name = 'terms synonym')

AttributeError: 'TOMWrapper' object has no attribute 'set_synonym'

**Comment by pawarbi** [comment]
Below worked for me without any errors. I installed 0.11.2

```
import sempy.fabric as fabric
import sempy_labs as labs
from sempy_labs.tom import connect_semantic_model

dataset = "Sales Custom Dataset"
workspace = "Sales"

with connect_semantic_model(dataset=dataset, workspace=workspace, readonly=False) as tom:
    table_obj = tom.model.Tables['products']
    tom.set_synonym(
        culture='en-US',
        object=table_obj,
        synonym_name='widgets'
    )
```

**Comment by aakashb14** [comment]
Thanks this worked with 0.11.2
